# docker-compose.yml
networks:
  todoapp-net:
services:
  pythonapp:
    image: todoapp:2.0.0
    build:
      context: ./todoapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./todoapp/app.env
    environment:
      PYTHONUNBUFFERED: "1"
    networks:
      - todoapp-net
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
  mysql:
    image: mysql-local:1.0.0
    build:
      context: ./mysql
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306" # should exist only for local development
    volumes:
      - todoapp-db-data:/var/lib/mysql
    env_file:
      - ./mysql/mysql.env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD --silent"] #$$ Проблема була в ранній інтерполяції Compose.
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - todoapp-net
    restart: unless-stopped
volumes:
  todoapp-db-data:
